// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnD2U-gfpCTUgFCH9ABa_LANgNTSLjfjg',
    appId: '1:832659153323:web:ff23841e9ed620b95632ee',
    messagingSenderId: '832659153323',
    projectId: 'wastenot-b32d2',
    authDomain: 'wastenot-b32d2.firebaseapp.com',
    storageBucket: 'wastenot-b32d2.appspot.com',
    measurementId: 'G-JDPR7NY9S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-XGnJ3o4xqnAnIq-S7UzkfxGyvYS1As',
    appId: '1:832659153323:android:a3f4cf087ea0d71b5632ee',
    messagingSenderId: '832659153323',
    projectId: 'wastenot-b32d2',
    storageBucket: 'wastenot-b32d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP3DsM0RNb92XRWCqYp1RGNPbDxs-pD80',
    appId: '1:832659153323:ios:b85c6dd2823422ef5632ee',
    messagingSenderId: '832659153323',
    projectId: 'wastenot-b32d2',
    storageBucket: 'wastenot-b32d2.appspot.com',
    iosBundleId: 'com.example.wasteNot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP3DsM0RNb92XRWCqYp1RGNPbDxs-pD80',
    appId: '1:832659153323:ios:b85c6dd2823422ef5632ee',
    messagingSenderId: '832659153323',
    projectId: 'wastenot-b32d2',
    storageBucket: 'wastenot-b32d2.appspot.com',
    iosBundleId: 'com.example.wasteNot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnD2U-gfpCTUgFCH9ABa_LANgNTSLjfjg',
    appId: '1:832659153323:web:242ae3347a5a22f75632ee',
    messagingSenderId: '832659153323',
    projectId: 'wastenot-b32d2',
    authDomain: 'wastenot-b32d2.firebaseapp.com',
    storageBucket: 'wastenot-b32d2.appspot.com',
    measurementId: 'G-BC35YCL2LX',
  );
}
